### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lukajo123** [Shkyyl/KeyChamp#4]
it's not joining battles

**Comment by Shkyyl** [comment]
all works fine, but when the traffic is heavy and cases are appearing too fast there is a chance to not join battle cause my script only works for 3 first cases on the site, so when 5 case battles are created suddenly at a time, script may not a catch the battle
you can change in script to for example 5 cases at the end of line 10,11 ```const caseNames = (([...document.querySelectorAll('p.max-w-full.px-1.overflow-hidden')]).splice(0,  here --> 3)).map(e => e.textContent);
      const casePrices = (([...document.querySelectorAll('div.flex.items-center.justify-center.rounded-tl-lg')]).splice(0, and here --> 3)).map(e => e.textContent); ``` and then should work fine
