### ISSUE TITLE
How about taking place in battle automatically?

### ISSUE THREAD

**Issue by cooligus** [Shkyyl/KeyChamp#7]
Ok. I have joined the battle, but I also need to take place in it manually.

**Comment by Shkyyl** [comment]
It's hard to do but i don't give up,

**Comment by HUAAKANU** [comment]
Are you still trying to do it because i need it so much.

**Comment by Shkyyl** [comment]
yes but i told already it's hard for me (i hate javascript)
> Are you still trying to do it because i need it so much.
